### ISSUE TITLE
Error while calling lua chunk - Neovim version 0.5

### ISSUE THREAD

**Issue by daniel-rajakumar** [GustavoPrietoP/neovim#1]
Hello fellow neovimers , I'm getting an error while opening neovim after installing this "evil" plugin. I've also tried running ```:PackerSync``` inside neovim. It throws an error saying ```...Not an editor command: WhichKey '  ' ```

When opening Neovim after installing.
![image](https://user-images.githubusercontent.com/55865975/116013742-a9dcde80-a5ff-11eb-94c0-c53c32c5bdab.png)

After running ```:packerSync```
![image](https://user-images.githubusercontent.com/55865975/116013828-28d21700-a600-11eb-8d03-e698c5fcb1ad.png)

Any help is welcome :)

Thanks, 
Daniel

Happy neoviming.

**Comment by GustavoPrietoP** [comment]
I'm aware of this issue. Working on a solution right now, if anyone wants to help out you are more than welcome to do so.

**Comment by TarunDaCoder** [comment]
Daniel, do you have the doom-one colourscheme installed in neovim?

**Comment by GustavoPrietoP** [comment]
Closing issue due to not using packer anymore.

**Comment by TarunDaCoder** [comment]
changing to paq?
