### ISSUE TITLE
How does this compare to https://github.com/NTBBloodbath/doom-nvim?

### ISSUE THREAD

**Issue by kuator** [GustavoPrietoP/neovim#5]
How does this compare to https://github.com/NTBBloodbath/doom-nvim?

**Comment by GustavoPrietoP** [comment]
Hey! I have stopped working on this config (as you can prob see by the inactive commits) and now I'm working with NTB and his doom-nvim config. We share the same goals and there is no reason for us to be working separately (at least in my eyes). We will continue to work towards the same goal just in a different repository :)

**Comment by kuator** [comment]
Pog!
